apply plugin: 'com.android.application'

android {
namespace 'com.androidstudy.andelamedmanager'
    compileSdkVersion 36
    defaultConfig {
        applicationId "com.androidstudy.andelamedmanager"
        minSdkVersion 21
        targetSdk 36
        versionCode 1
        versionName "1.0"
        vectorDrawables.useSupportLibrary true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }


    packaging {
        resources {
            excludes += ['META-INF/INDEX.LIST', 'META-INF/DEPENDENCIES']
        }
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        buildConfig true
        viewBinding true
        dataBinding true
    }

    viewBinding {
        enabled = true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // AndroidX Replacements for old support libs
    implementation deps.support.appcompat
    implementation deps.support.design

    // Room - Sqlite Wrapper
    implementation deps.room.core
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    annotationProcessor deps.room.compiler

    implementation 'com.google.api-client:google-api-client-android:2.8.1'
    implementation 'com.google.apis:google-api-services-drive:v3-rev20220815-2.0.0'
    implementation 'com.google.api-client:google-api-client-gson:2.8.1'
    implementation 'com.google.http-client:google-http-client-android:2.0.0'
    implementation "androidx.work:work-runtime:2.10.3"
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'

    // RxJava and RxAndroid
    implementation deps.rxjava2
    implementation deps.rxandroid2

    // Log - Replace the Android Log Class
    implementation deps.timber

    // My Lib -> Monitor Internet Connectivity
    implementation project(":networkmanager")

    // Dagger 2 - Dependency Injection
    implementation deps.dagger.core
    annotationProcessor deps.dagger.compiler
    compileOnly deps.jsr250api

    // Glide - Handle Images
    implementation deps.glide.core
    annotationProcessor deps.glide.compiler

    // Recycler View Snap Helper
    implementation deps.snaphelper

    // Circular Profile ImageView
    implementation deps.circleImageView

    // Material Dialogs alt alert dialogs
    implementation deps.materialDialogs.core

    // Progress SnackBar
    implementation deps.snackProgressBar

    // Google Auth & Drive
    implementation deps.playServices.auth
    implementation deps.playServices.drive

    // State saving/restoring
    implementation deps.state.core
    annotationProcessor deps.state.processor

    // Added Spark
    implementation deps.spark

    // Circular Progress Bar
    // implementation deps.circleProgress

    // Testing !!!
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    androidTestImplementation('androidx.test.espresso:espresso-contrib:3.5.1') {
        exclude group: 'androidx.annotation', module: 'annotation'
        exclude group: 'androidx.legacy', module: 'legacy-support-v4'
        exclude group: 'com.google.android.material', module: 'material'
        exclude group: 'androidx.recyclerview', module: 'recyclerview'
    }
}

apply plugin: 'com.google.gms.google-services'
